<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class PatientSeeder extends Seeder
{
    /**
     * Seed the patients table with realistic sample data.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('patients')->truncate();
        Schema::enableForeignKeyConstraints();

        $now = now();

        // ------------------------------------------------------------------
        // 15 City Care Hospital patients (Indian names, +91 phones)
        // First 10 use SeedData constants, remaining 5 use Str::uuid()
        // ------------------------------------------------------------------
        $cityPatients = [
            [
                'id'                 => SeedData::PATIENT_01,
                'name'               => 'Arun Krishnamurthy',
                'date_of_birth'      => '1985-03-15',
                'gender'             => 'male',
                'phone'              => '+919876543210',
                'email'              => 'arun.k@gmail.com',
                'address'            => '12, Indiranagar, Bangalore',
                'blood_group'        => 'B+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Sunita Krishnamurthy',
                'emergency_contact_phone' => '+919876543200',
                'medical_history'    => ['Diabetes Type 2', 'Hypertension'],
                'current_medications'=> ['Metformin 500mg', 'Amlodipine 5mg'],
                'allergies'          => ['Penicillin'],
                'insurance_details'  => ['insurer' => 'Star Health', 'policy_number' => 'SH-2024-98234', 'member_id' => 'MEM-44821'],
                'metadata'           => ['referral_source' => 'google'],
                'created_via'        => 'whatsapp',
            ],
            [
                'id'                 => SeedData::PATIENT_02,
                'name'               => 'Kavitha Ramesh',
                'date_of_birth'      => '1992-07-22',
                'gender'             => 'female',
                'phone'              => '+919876543211',
                'email'              => 'kavitha.r@yahoo.com',
                'address'            => '45, Jayanagar, Bangalore',
                'blood_group'        => 'O+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Ramesh S',
                'emergency_contact_phone' => '+919876543201',
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'web',
            ],
            [
                'id'                 => SeedData::PATIENT_03,
                'name'               => 'Raju Venkatesh',
                'date_of_birth'      => '1958-11-03',
                'gender'             => 'male',
                'phone'              => '+919876543212',
                'email'              => null,
                'address'            => '78, Basavanagudi, Bangalore',
                'blood_group'        => 'A+',
                'language_preference'=> 'hi',
                'emergency_contact_name'  => 'Suresh Venkatesh',
                'emergency_contact_phone' => '+919876543202',
                'medical_history'    => ['Hypertension', 'Arthritis'],
                'current_medications'=> ['Amlodipine 5mg', 'Ibuprofen 400mg'],
                'allergies'          => ['Sulfa drugs'],
                'insurance_details'  => ['insurer' => 'Star Health', 'policy_number' => 'SH-2024-76543', 'member_id' => 'MEM-33210'],
                'metadata'           => ['needs_wheelchair' => true],
                'created_via'        => 'walk_in',
            ],
            [
                'id'                 => SeedData::PATIENT_04,
                'name'               => 'Priyanka Shetty',
                'date_of_birth'      => '2019-05-10',
                'gender'             => 'female',
                'phone'              => '+919876543213',
                'email'              => 'priyanka.parent@gmail.com',
                'address'            => '23, HSR Layout, Bangalore',
                'blood_group'        => 'B+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Deepa Shetty',
                'emergency_contact_phone' => '+919876543203',
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => ['Peanuts'],
                'insurance_details'  => null,
                'metadata'           => ['guardian' => 'Deepa Shetty'],
                'created_via'        => 'whatsapp',
            ],
            [
                'id'                 => SeedData::PATIENT_05,
                'name'               => 'Ganesh Hegde',
                'date_of_birth'      => '1975-09-18',
                'gender'             => 'male',
                'phone'              => '+919876543214',
                'email'              => 'ganesh.hegde@outlook.com',
                'address'            => '56, Whitefield, Bangalore',
                'blood_group'        => 'AB+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Lakshmi Hegde',
                'emergency_contact_phone' => '+919876543204',
                'medical_history'    => ['Diabetes Type 2'],
                'current_medications'=> ['Metformin 500mg', 'Glimepiride 1mg'],
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'ICICI Lombard', 'policy_number' => 'IL-2025-12345', 'member_id' => 'MEM-56789'],
                'metadata'           => null,
                'created_via'        => 'kiosk',
            ],
            [
                'id'                 => SeedData::PATIENT_06,
                'name'               => 'Lakshmi Narasimhan',
                'date_of_birth'      => '1968-02-25',
                'gender'             => 'female',
                'phone'              => '+919876543215',
                'email'              => null,
                'address'            => '34, Malleshwaram, Bangalore',
                'blood_group'        => 'O-',
                'language_preference'=> 'hi',
                'emergency_contact_name'  => 'Narasimhan K',
                'emergency_contact_phone' => '+919876543205',
                'medical_history'    => ['Hypertension', 'Hypothyroidism'],
                'current_medications'=> ['Losartan 50mg', 'Levothyroxine 50mcg'],
                'allergies'          => ['Aspirin'],
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'walk_in',
            ],
            [
                'id'                 => SeedData::PATIENT_07,
                'name'               => 'Kiran Joshi',
                'date_of_birth'      => '2015-12-08',
                'gender'             => 'male',
                'phone'              => '+919876543216',
                'email'              => 'kiran.parent@gmail.com',
                'address'            => '89, Electronic City, Bangalore',
                'blood_group'        => 'A+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Shweta Joshi',
                'emergency_contact_phone' => '+919876543206',
                'medical_history'    => ['Asthma'],
                'current_medications'=> ['Salbutamol inhaler'],
                'allergies'          => ['Dust mites'],
                'insurance_details'  => null,
                'metadata'           => ['guardian' => 'Shweta Joshi'],
                'created_via'        => 'whatsapp',
            ],
            [
                'id'                 => SeedData::PATIENT_08,
                'name'               => 'Meenakshi Iyer',
                'date_of_birth'      => '1990-04-30',
                'gender'             => 'female',
                'phone'              => '+919876543217',
                'email'              => 'meenakshi.iyer@gmail.com',
                'address'            => '67, BTM Layout, Bangalore',
                'blood_group'        => 'B-',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Suresh Iyer',
                'emergency_contact_phone' => '+919876543207',
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'Max Bupa', 'policy_number' => 'MB-2025-55432', 'member_id' => 'MEM-88901'],
                'metadata'           => null,
                'created_via'        => 'web',
            ],
            [
                'id'                 => SeedData::PATIENT_09,
                'name'               => 'Subramaniam Pillai',
                'date_of_birth'      => '1950-08-14',
                'gender'             => 'male',
                'phone'              => '+919876543218',
                'email'              => null,
                'address'            => '112, Rajajinagar, Bangalore',
                'blood_group'        => 'A-',
                'language_preference'=> 'hi',
                'emergency_contact_name'  => 'Meena Pillai',
                'emergency_contact_phone' => '+919876543208',
                'medical_history'    => ['COPD', 'Hypertension', 'Diabetes Type 2'],
                'current_medications'=> ['Tiotropium inhaler', 'Amlodipine 5mg', 'Metformin 1000mg'],
                'allergies'          => ['Penicillin', 'Sulfa drugs'],
                'insurance_details'  => ['insurer' => 'Star Health', 'policy_number' => 'SH-2024-33456', 'member_id' => 'MEM-11234'],
                'metadata'           => ['needs_wheelchair' => true],
                'created_via'        => 'walk_in',
            ],
            [
                'id'                 => SeedData::PATIENT_10,
                'name'               => 'Divya Menon',
                'date_of_birth'      => '1988-01-19',
                'gender'             => 'female',
                'phone'              => '+919876543219',
                'email'              => 'divya.menon@hotmail.com',
                'address'            => '28, Koramangala, Bangalore',
                'blood_group'        => 'O+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => ['PCOD'],
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'whatsapp',
            ],
            // Remaining 5 with generated UUIDs
            [
                'id'                 => Str::uuid()->toString(),
                'name'               => 'Vishnu Prasad',
                'date_of_birth'      => '2001-06-05',
                'gender'             => 'male',
                'phone'              => '+919876543220',
                'email'              => 'vishnu.p@gmail.com',
                'address'            => '5, Marathahalli, Bangalore',
                'blood_group'        => 'B+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'kiosk',
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'name'               => 'Savitri Deshpande',
                'date_of_birth'      => '1962-10-12',
                'gender'             => 'female',
                'phone'              => '+919876543221',
                'email'              => null,
                'address'            => '90, Vijayanagar, Bangalore',
                'blood_group'        => 'A+',
                'language_preference'=> 'hi',
                'emergency_contact_name'  => 'Mohan Deshpande',
                'emergency_contact_phone' => '+919876543221',
                'medical_history'    => ['Osteoporosis', 'Vitamin D Deficiency'],
                'current_medications'=> ['Calcium 500mg', 'Vitamin D3 60000IU weekly'],
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'Religare Health', 'policy_number' => 'RH-2025-44567', 'member_id' => 'MEM-22345'],
                'metadata'           => null,
                'created_via'        => 'walk_in',
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'name'               => 'Anand Kumar',
                'date_of_birth'      => '1995-03-28',
                'gender'             => 'male',
                'phone'              => '+919876543222',
                'email'              => 'anand.kumar95@gmail.com',
                'address'            => '15, Yelahanka, Bangalore',
                'blood_group'        => 'O+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => ['Ibuprofen'],
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'web',
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'name'               => 'Saroja Bhat',
                'date_of_birth'      => '1978-07-07',
                'gender'             => 'female',
                'phone'              => '+919876543223',
                'email'              => 'saroja.bhat@yahoo.com',
                'address'            => '102, JP Nagar, Bangalore',
                'blood_group'        => 'AB-',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => ['Migraine'],
                'current_medications'=> ['Sumatriptan 50mg as needed'],
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'whatsapp',
            ],
            [
                'id'                 => Str::uuid()->toString(),
                'name'               => 'Ramesh Gowda',
                'date_of_birth'      => '1970-12-01',
                'gender'             => 'male',
                'phone'              => '+919876543224',
                'email'              => null,
                'address'            => '76, Hebbal, Bangalore',
                'blood_group'        => 'B+',
                'language_preference'=> 'hi',
                'emergency_contact_name'  => 'Gowda Family',
                'emergency_contact_phone' => '+919876543224',
                'medical_history'    => ['Diabetes Type 2', 'Chronic Kidney Disease Stage 2'],
                'current_medications'=> ['Metformin 500mg', 'Telmisartan 40mg'],
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'Star Health', 'policy_number' => 'SH-2025-87654', 'member_id' => 'MEM-66543'],
                'metadata'           => null,
                'created_via'        => 'kiosk',
            ],
        ];

        foreach ($cityPatients as $p) {
            DB::table('patients')->insert([
                'id'                      => $p['id'],
                'hospital_id'             => SeedData::CITY_CARE_ID,
                'phone'                   => $p['phone'],
                'phone_verified'          => true,
                'name'                    => $p['name'],
                'email'                   => $p['email'],
                'date_of_birth'           => $p['date_of_birth'],
                'age_approximate'         => null,
                'gender'                  => $p['gender'],
                'blood_group'             => $p['blood_group'],
                'language_preference'     => $p['language_preference'],
                'address'                 => $p['address'],
                'city'                    => 'Bangalore',
                'emergency_contact_name'  => $p['emergency_contact_name'],
                'emergency_contact_phone' => $p['emergency_contact_phone'],
                'medical_history'         => $p['medical_history'] ? json_encode($p['medical_history']) : null,
                'allergies'               => $p['allergies'] ? json_encode($p['allergies']) : null,
                'current_medications'     => $p['current_medications'] ? json_encode($p['current_medications']) : null,
                'insurance_details'       => $p['insurance_details'] ? encrypt(json_encode($p['insurance_details'])) : null,
                'metadata'                => $p['metadata'] ? json_encode($p['metadata']) : null,
                'created_via'             => $p['created_via'],
                'created_at'              => $now->copy()->subDays(rand(1, 90)),
                'updated_at'              => $now,
            ]);
        }

        // ------------------------------------------------------------------
        // 8 Gulf Medical Center patients (Arabic/international names, +971)
        // ------------------------------------------------------------------
        $gulfPatients = [
            [
                'name'               => 'Mohammed Al-Mansoori',
                'date_of_birth'      => '1980-05-12',
                'gender'             => 'male',
                'phone'              => '+971501112233',
                'email'              => 'mohammed.m@gmail.com',
                'address'            => 'Al Barsha 2, Dubai',
                'blood_group'        => 'O+',
                'language_preference'=> 'ar',
                'emergency_contact_name'  => 'Fatima Al-Mansoori',
                'emergency_contact_phone' => '+971501112234',
                'medical_history'    => ['Diabetes Type 2'],
                'current_medications'=> ['Metformin 500mg'],
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'Daman', 'policy_number' => 'DAM-2025-11234', 'member_id' => 'DM-55678'],
                'metadata'           => null,
                'created_via'        => 'whatsapp',
            ],
            [
                'name'               => 'Aisha Al-Hashimi',
                'date_of_birth'      => '1993-02-18',
                'gender'             => 'female',
                'phone'              => '+971502223344',
                'email'              => 'aisha.h@outlook.com',
                'address'            => 'Jumeirah, Dubai',
                'blood_group'        => 'A+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'NAS', 'policy_number' => 'NAS-2025-22345', 'member_id' => 'NAS-66789'],
                'metadata'           => null,
                'created_via'        => 'web',
            ],
            [
                'name'               => 'Yusuf Khan',
                'date_of_birth'      => '1965-11-29',
                'gender'             => 'male',
                'phone'              => '+971503334455',
                'email'              => null,
                'address'            => 'Deira, Dubai',
                'blood_group'        => 'B+',
                'language_preference'=> 'ar',
                'emergency_contact_name'  => 'Ahmed Khan',
                'emergency_contact_phone' => '+971503334456',
                'medical_history'    => ['Hypertension', 'Hyperlipidemia'],
                'current_medications'=> ['Amlodipine 5mg', 'Atorvastatin 20mg'],
                'allergies'          => ['Penicillin'],
                'insurance_details'  => ['insurer' => 'Daman', 'policy_number' => 'DAM-2025-33456', 'member_id' => 'DM-77890'],
                'metadata'           => null,
                'created_via'        => 'walk_in',
            ],
            [
                'name'               => 'Sara Al-Suwaidi',
                'date_of_birth'      => '2018-07-04',
                'gender'             => 'female',
                'phone'              => '+971504445566',
                'email'              => 'sara.parent@gmail.com',
                'address'            => 'Marina, Dubai',
                'blood_group'        => 'O+',
                'language_preference'=> 'en',
                'emergency_contact_name'  => 'Noura Al-Suwaidi',
                'emergency_contact_phone' => '+971504445567',
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => ['guardian' => 'Noura Al-Suwaidi'],
                'created_via'        => 'whatsapp',
            ],
            [
                'name'               => 'Hassan Al-Falasi',
                'date_of_birth'      => '1955-03-22',
                'gender'             => 'male',
                'phone'              => '+971505556677',
                'email'              => null,
                'address'            => 'Bur Dubai, Dubai',
                'blood_group'        => 'AB+',
                'language_preference'=> 'ar',
                'emergency_contact_name'  => 'Omar Al-Falasi',
                'emergency_contact_phone' => '+971505556678',
                'medical_history'    => ['Coronary Artery Disease', 'Diabetes Type 2'],
                'current_medications'=> ['Aspirin 75mg', 'Metformin 1000mg', 'Atorvastatin 40mg'],
                'allergies'          => ['Sulfa drugs'],
                'insurance_details'  => ['insurer' => 'Daman', 'policy_number' => 'DAM-2025-44567', 'member_id' => 'DM-88901'],
                'metadata'           => null,
                'created_via'        => 'walk_in',
            ],
            [
                'name'               => 'Mariam Abbas',
                'date_of_birth'      => '1987-09-15',
                'gender'             => 'female',
                'phone'              => '+971506667788',
                'email'              => 'mariam.abbas@gmail.com',
                'address'            => 'JLT, Dubai',
                'blood_group'        => 'A-',
                'language_preference'=> 'en',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'NAS', 'policy_number' => 'NAS-2025-55678', 'member_id' => 'NAS-99012'],
                'metadata'           => null,
                'created_via'        => 'kiosk',
            ],
            [
                'name'               => 'Abdullah Rashid',
                'date_of_birth'      => '1999-01-08',
                'gender'             => 'male',
                'phone'              => '+971507778899',
                'email'              => 'abdullah.r@hotmail.com',
                'address'            => 'Silicon Oasis, Dubai',
                'blood_group'        => 'B-',
                'language_preference'=> 'ar',
                'emergency_contact_name'  => null,
                'emergency_contact_phone' => null,
                'medical_history'    => null,
                'current_medications'=> null,
                'allergies'          => null,
                'insurance_details'  => null,
                'metadata'           => null,
                'created_via'        => 'whatsapp',
            ],
            [
                'name'               => 'Noura Al-Ketbi',
                'date_of_birth'      => '1975-06-20',
                'gender'             => 'female',
                'phone'              => '+971508889900',
                'email'              => null,
                'address'            => 'Al Quoz, Dubai',
                'blood_group'        => 'O+',
                'language_preference'=> 'ar',
                'emergency_contact_name'  => 'Khalid Al-Ketbi',
                'emergency_contact_phone' => '+971508889901',
                'medical_history'    => ['Hypothyroidism'],
                'current_medications'=> ['Levothyroxine 50mcg'],
                'allergies'          => null,
                'insurance_details'  => ['insurer' => 'Daman', 'policy_number' => 'DAM-2025-66789', 'member_id' => 'DM-11234'],
                'metadata'           => null,
                'created_via'        => 'walk_in',
            ],
        ];

        foreach ($gulfPatients as $p) {
            DB::table('patients')->insert([
                'id'                      => Str::uuid()->toString(),
                'hospital_id'             => SeedData::GULF_MEDICAL_ID,
                'phone'                   => $p['phone'],
                'phone_verified'          => true,
                'name'                    => $p['name'],
                'email'                   => $p['email'],
                'date_of_birth'           => $p['date_of_birth'],
                'age_approximate'         => null,
                'gender'                  => $p['gender'],
                'blood_group'             => $p['blood_group'],
                'language_preference'     => $p['language_preference'],
                'address'                 => $p['address'],
                'city'                    => 'Dubai',
                'emergency_contact_name'  => $p['emergency_contact_name'],
                'emergency_contact_phone' => $p['emergency_contact_phone'],
                'medical_history'         => $p['medical_history'] ? json_encode($p['medical_history']) : null,
                'allergies'               => $p['allergies'] ? json_encode($p['allergies']) : null,
                'current_medications'     => $p['current_medications'] ? json_encode($p['current_medications']) : null,
                'insurance_details'       => $p['insurance_details'] ? encrypt(json_encode($p['insurance_details'])) : null,
                'metadata'                => $p['metadata'] ? json_encode($p['metadata']) : null,
                'created_via'             => $p['created_via'],
                'created_at'              => $now->copy()->subDays(rand(1, 60)),
                'updated_at'              => $now,
            ]);
        }
    }
}
